### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-06-18/Keoni-G#2]
https://github.com/CodingDojo-MEAN-06-18/Keoni-G/blob/937535fa15b1e3f52a09a7ae69f0e4f6dcbbe2a0/MEAN1/Week1/NinjaClasses/III/ninja.js#L2-L7

Instead of using a ternary why not set a default value for name? 

```javascript 
class Ninja {
    constructor(name = "Unknown Ninja") {
        this.name = name;
        this.health = 100;
        this.speed = 3;
        this.strength = 3;
    }
}
```

**Comment by ObiWanKeoni** [comment]
Good call! I have no idea why I decided to use a ternary...
