### ISSUE TITLE
Observables

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-06-18/Keoni-G#4]
https://github.com/CodingDojo-MEAN-06-18/Keoni-G/blob/50b1f477c1c97f2eb7532c17afc8fc5682ae16ea/MEAN2/Optional/Numbers-In-Services/src/app/task.service.ts#L6-L9

After you read about `Observables` consider refactoring this assignment (and NinjaGold) to use a `BehaviorSubject` rather than using arrays of values for `differences`.

**Comment by ObiWanKeoni** [comment]
How does that look?
